# Generated by Django 3.0.7 on 2020-06-10 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('criminal_justice', models.SmallIntegerField()),
                ('economy_taxes', models.SmallIntegerField()),
                ('education', models.SmallIntegerField()),
                ('minority_support', models.SmallIntegerField()),
                ('immigration', models.SmallIntegerField()),
                ('environment', models.SmallIntegerField()),
                ('lbgtq_rights', models.SmallIntegerField()),
                ('womens_rights', models.SmallIntegerField()),
                ('health_care', models.SmallIntegerField()),
                ('corporations', models.SmallIntegerField()),
                ('national_security', models.SmallIntegerField()),
                ('gun_control', models.SmallIntegerField()),
                ('social_left_to_right', models.SmallIntegerField()),
                ('economics_left_to_right', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Preference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('up_for_re_election', models.BooleanField(max_length=100)),
                ('biography', models.BooleanField(max_length=100)),
                ('criminal_justice', models.CharField(max_length=1000)),
                ('economy_taxes', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=1000)),
                ('minority_support', models.CharField(max_length=1000)),
                ('immigration', models.CharField(max_length=1000)),
                ('environment', models.CharField(max_length=1000)),
                ('lbgtq_rights', models.CharField(max_length=1000)),
                ('womens_rights', models.CharField(max_length=1000)),
                ('health_care', models.CharField(max_length=1000)),
                ('corporations', models.CharField(max_length=1000)),
                ('national_security', models.CharField(max_length=1000)),
                ('gun_control', models.CharField(max_length=1000)),
                ('preference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Preference')),
            ],
        ),
    ]
