# Generated by Django 3.0.7 on 2020-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='economics_left_to_right',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='social_left_to_right',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
