# Generated by Django 3.0.7 on 2020-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='abortion',
            field=models.SmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
