# Generated by Django 3.0.7 on 2020-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_preference_abortion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politician',
            old_name='up_for_re_election',
            new_name='up_for_election',
        ),
        migrations.AlterField(
            model_name='politician',
            name='biography',
            field=models.CharField(max_length=1000),
        ),
    ]
