# Generated by Django 3.0.7 on 2020-06-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200610_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='abortion',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
