# Generated by Django 3.0.7 on 2020-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_politician_abortion'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='image',
            field=models.ImageField(default='profile-blank.png', upload_to='profile_pics'),
        ),
    ]
