# Generated by Django 2.0.5 on 2020-08-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
