# Generated by Django 2.0.5 on 2020-08-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_events_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
