# Generated by Django 2.0.5 on 2020-08-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200801_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='profile-blank.png', upload_to='event_pics'),
        ),
    ]
