# Generated by Django 2.0.5 on 2020-08-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200802_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='profile-blank.png', upload_to='event_pics')),
                ('mission', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
