# Generated by Django 2.0.5 on 2020-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200813_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='image',
            field=models.ImageField(default='group-blank.png', upload_to='movement_pics'),
        ),
    ]
